// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './app/hello.fixture';
import * as fixture1 from './app/cards/CardItem.fixture';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5000"
};

const fixtures = {
  'app/hello.fixture.tsx': { module: fixture0 },
  'app/cards/CardItem.fixture.tsx': { module: fixture1 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
